apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgrepack-masudastream
  labels:
    app: pgrepack-masudastream
spec:
  schedule: "18 16 * * 3"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pgrepack-masudastream
        spec:
          volumes:
            - name: pgpass
              configMap:
                name: prepare-pgpass
                defaultMode: 0777
          containers:
            - name: pgrepack
              image: ghcr.io/h3poteto/pg_repack:1.5.2-1
              imagePullPolicy: Always
              command: ["/var/opt/script/generate_pgpass.sh"]
              args: ["pg_repack", "-h", "$(DB_HOST)", "-U", "$(DB_USER)", "-k", "-d", "masuda_stream"]
              envFrom:
                - secretRef:
                    name: masudastream-db-env
              env:
                - name: DB_HOST
                  value: nyaruko.cju8robzjmqc.ap-northeast-1.rds.amazonaws.com
              volumeMounts:
                - name: pgpass
                  mountPath: /var/opt/script
              resources:
                requests:
                  memory: 500Mi
                  cpu: 500m
          restartPolicy: Never
      backoffLimit: 0
