#!/bin/bash

function enc {
    bundle exec yaml_vault encrypt $2 -o $3 --key=$1 --cryptor=aws-kms --aws-kms-key-id=803db205-6479-4a08-8a08-eddbfc2e2925
}

function dec {
    bundle exec yaml_vault decrypt $2 -o $3 --key=$1 --cryptor=aws-kms
}

if [ $# -ne 4 ]; then
    echo "vault (encrypt|decrypt) key input_file output_file"
    exit 1
fi

case "$1" in
    encrypt)
        enc $2 $3 $4
        ;;
    decrypt)
        dec $2 $3 $4
        ;;
    *)
        echo "vault (encrypt|decrypt) input_file output_file"
        exit 1
        ;;
esac
