apiVersion: elbv2.k8s.aws/v1alpha1
kind: TargetGroupBinding
metadata:
  name: whalebird
spec:
  serviceRef:
    name: whalebird-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-1:564677439943:targetgroup/whalebird/bd99b4d7217579aa
  targetType: instance
